HOMEPAGE_H1_TEXT = "AutomationExercise"
HOMEPAGE_URL = "http://automationexercise.com"
LOGIN_PAGE_URL = "https://automationexercise.com/login"
SIGNUP_FORM_TITLE = "New User Signup!"
NAME = "John"
LAST_NAME = "Doe"
COMPANY = "Fake Inc."
ADDRESS1 = "Fake address 1"
ADDRESS2 = "Fake address 2"
COUNTRY = "Canada"
STATE = "Ontario"
CITY = "Toronto"
ZIP = "111111111"
PHONE_NUM = "416000000000"
EMAIL = "john.doe1234@email.com"
DOB = {
    "day": "1",
    "month": "January",
    "year": "1991"
}
PASSWORD = "!@#$%^&*"
TITLE = "mrs"
SIGNUP_PAGE_TITLE = "ENTER ACCOUNT INFORMATION"
ACCOUNT_CREATED_TITLE = "ACCOUNT CREATED!"
ACCOUNT_DELETED_TITLE = "ACCOUNT DELETED!"
CONTINUE_BTN_SELECTOR = "a[data-qa='continue-button']"
ACC_CREATED_TITLE_SELECTOR = "h2[data-qa='account-created']"
ACC_DELETED_TITLE_SELECTOR = "h2[data-qa='account-deleted']"